force-app/main/default/objects/Integration_Config__mdt/Integration_Config__mdt.object-meta.xml
<CustomObject>
    <description>Stores integration configuration records that act as mappings of integration classes with their configurations so that the concrete integration classes we have can be determined at runtime rather than every developer needing to update the integration framework code to add their class manually.</description>
    <label>Integration Config</label>
    <pluralLabel>Integration Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Config__mdt/fields/RetentionDaysNum__c.field-meta.xml
<CustomField>
    <fullName>RetentionDaysNum__c</fullName>
    <description>Stores the length of retention policy in days for this integration configuration</description>
    <label>Retention Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IntegrationMessage__c/IntegrationMessage__c.object-meta.xml
<CustomObject>
    <description>Stores records representing integration messages between Salesforce and external systems</description>
    <label>Integration Message</label>
    <nameField>
        <label>Integration Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/INT_MessageArchiveBatch.cls
public class INT_MessageArchiveBatch imlements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext context) {
        Date cutoffDate = date.today().addDays(-getMaxRetentionDays());
        return Database.getQueryLocator([
            SELECT Id
            FROM IntegrationMessage__c
            WHERE MessageTimeStampDT__c < :cutoffDate
        ]);
    }

    public execute(Database.BatchableContext context, List<IntegrationMessage__c> records) {
        delete records;
    }

    public finish(Database.BatchableContext context) {
        private Integer getMaxRetentionDays() {
        Integer maxDays = 0;
        for(Integration_Config__mdt config : INT_ConfigProvider.getAllConfigs().values()) {
            if(config.RetentionDaysNum__c != null && config.RetentionDaysNum__c > maxDays) {
                maxDays = Integer.valueOf(config.RetentionDaysNum__c);
            }
        }
        return maxDays > 0 ? maxDays : 90;
    }
}