force-app/main/default/objects/Integration_Config__mdt/Integration_Config__mdt.object-meta.xml
<CustomObject>
    <description>Stores integration configuration records that act as mappings of integration classes with their configurations so that the concrete integration classes we have can be determined at runtime rather than every developer needing to update the integration framework code to add their class manually.</description>
    <label>Integration Config</label>
    <pluralLabel>Integration Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Config__mdt/fields/MessageTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>MessageTypeTxt__c</fullName>
    <description>Stores the type of message</description>
    <label>Message Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/INT_ConfigProvider.cls
public class INT_ConfigProvider {
    private static Map<String, Integration_Config__mdt> configByMessageType;

    public static Map<String, Integration_Config__mdt> getAllConfigs() {
        if(configByMessageType == null) {
            configByMessageType = new Map<String, Integration_Config__mdt>();

            Map<String, Integration_Config__mdt> allRecords = Integration_Config__mdt.getAll();
            for(Integration_Config__mdt config : allRecords.values()) {
                configByMessageType.put(config.MessageTypeTxt__c, config);
            }
        }
        return configByMessageType;

    }
    
    public static Integration_Config__mdt getConfig(String messageType) {
        Integration_Config__mdt config = getAllConfigs().get(messageType);
        if(config == null) {
            throw new INT_HandlerNotFoundException('No configuration found for messageType: ' + messageType
            );
        }
        return config;
    }
}